<h1>Main information</h1>

<p><strong>Project:</strong> $PROJECT_NAME$</p>
<p><strong>File:</strong> $PROJECT_FILE$</p>
<p><strong>Checked links:</strong> $CHECKED_LINKS$</p>
<p><strong>Report date:</strong> $REPORT_DATE$</p>
$if(REPORT_RESULT)$
	<p><strong>State:</strong> <span style="color: green;">Passed</span></p>
$else$
	<p><strong>State:</strong> <span style="color: red;">Not Passed</span></p>
$endif$

<p><strong>You will find the report attached.</strong></p>

<p>This email was sent from Revit through Add-in ExportTablaAreas ($VERSION$)</p>